development:
  adapter: sqlite3
  encoding: utf-8
  database: postapp
  pool: 2
  username:
  password:

production:
  adapter: sqlite3
  encoding: utf-8
  database: postapp
  pool: 2
  username:
  password: